name: Aubio Beat Detector
version: "1.0"
slug: aubio_beat
description: Detects beats in audio streams using aubio and exposes them via HTTP
url: https://github.com/dein-name/aubio_beat_addon
startup: services
boot: auto
arch:
  - amd64
  - aarch64
  - armv7
  - armhf
  - i386
map:
  - share:rw
ports:
  5000/tcp: 5000
options:
  log_level:
    type: string
    default: DEBUG
    description: "Set the logging level"
    example: DEBUG
    options:
      DEBUG: "Debug level, detailed information"
      INFO: "Info level, general runtime events"
      WARNING: "Warning level, something unexpected happened"
      ERROR: "Error level, serious problems"
      CRITICAL: "Critical level, very serious errors"
  fifo_path: /share/snapfifo/snapfifo
schema:
  fifo_path: str
  log_level: str