name: snapcast-server
version: '0.28.0-r1'
slug: snapcastserver
description: Snapcast Server
panel_icon: mdi:music-box-outline
url: https://github.com/rw-django-fan-2020/hassio-addons/tree/master/snapcastserver
ingress: true
ingress_port: 1780
startup: system
boot: auto
init: false
map:
- share:rw
options:
  use_custom_config: false
  stream:
    sources:
    - pipe:///share/snapfifo/snapfifo?name=default
    - pipe:///share/snapfifo/librespot?name=SpotifyConnect&sampleformat=44100:16:2
    - pipe:///share/snapfifo/mopidy?name=Mopidy&sampleformat=44100:16:2
    - tcp://0.0.0.0?port=4953&name=snapbroadcast
    buffer: 1000
    codec: flac
    send_to_muted: 'false'
    sampleformat: '48000:16:2'
  http:
    enabled: 'true'
    doc_root: " "
  tcp:
    enabled: 'true'
  logging:
    enabled: 'true'
  server:
    threads: "-1"
    datadir: "/share/snapcast/"
schema:
  use_custom_config: bool
  stream:
    sources:
    - str?
    buffer: int?
    codec: str?
    send_to_muted: str?
    sampleformat: str?
  http:
    enabled: str?
    doc_root: str?
  tcp:
    enabled: str?
  logging:
    enabled: str?
  server:
    threads: int?
    datadir: str?
ports:
  1704/tcp: 1704
  1705/tcp: 1705
  1780/tcp: 1780
#  4953/tcp: 4953
ports_description:
  1704/tcp: which port the server should listen to
  1705/tcp: TCP Json RPC
  1780/tcp: HTTP Json RPC (if enabled)
#  4953/tcp: HTTPd Connection (if enabled)
arch:
- armhf
- armv7
- aarch64
- amd64
- i386
