build_from:
  armhf: ghcr.io/home-assistant/armhf-base:3.19
  armv7: ghcr.io/home-assistant/armv7-base:3.19
  aarch64: ghcr.io/home-assistant/aarch64-base:3.19
  amd64: ghcr.io/home-assistant/amd64-base:3.19
  i386: ghcr.io/home-assistant/i386-base:3.19

#https://pkgs.alpinelinux.org/packages?name=mpc&branch=v3.19&repo=&arch=&maintainer=
#https://pkgs.alpinelinux.org/packages?name=mpd&branch=v3.19&repo=&arch=&maintainer=
#https://pkgs.alpinelinux.org/packages?name=ympd&branch=v3.19&repo=&arch=&maintainer=
args:
  MPC_VERSION: "0.34-r0"
  MPD_VERSION: "0.23.14-r1"
  YMPD_VERSION: "1.3.0-r12"