build_from:
  armhf: ghcr.io/home-assistant/armhf-base:3.22
  armv7: ghcr.io/home-assistant/armv7-base:3.22
  aarch64: ghcr.io/home-assistant/aarch64-base:3.22
  amd64: ghcr.io/home-assistant/amd64-base:3.22
  i386: ghcr.io/home-assistant/i386-base:3.22

#https://pkgs.alpinelinux.org/packages?name=mpc&branch=v3.22&repo=&arch=&origin=&flagged=&maintainer=
#https://pkgs.alpinelinux.org/packages?name=mpd&branch=v3.22&repo=&arch=&origin=&flagged=&maintainer=
#https://pkgs.alpinelinux.org/packages?name=mympd&branch=v3.22&repo=&arch=&origin=&flagged=&maintainer=
args:
  MPC_VERSION: "0.35-r0"
  MPD_VERSION: "0.24.4-r1"
  MYMPD_VERSION: "21.0.0-r0"