build_from:
  armhf: ghcr.io/home-assistant/armhf-base:3.19
  armv7: ghcr.io/home-assistant/armv7-base:3.19
  aarch64: ghcr.io/home-assistant/aarch64-base:3.19
  amd64: ghcr.io/home-assistant/amd64-base:3.19
  i386: ghcr.io/home-assistant/i386-base:3.19

#https://pkgs.alpinelinux.org/packages?name=openssl*&branch=v3.19&repo=&arch=&maintainer=
args:
  OPENSSL_VERSION: "3.1.4-r6"